### ISSUE TITLE
Upgrade the Gradle version for building

### ISSUE THREAD

**Issue by sschuberth** [GradleUp/gr8#21]
For the fun of it, I tried upgrading the Gradle version used for the build to latest 8.10.2, but it failed as `DefaultSelfResolvingDependency` was deprecated in Gradle 8.7 in favor of `DefaultFileCollectionDependency`.

So I tried upgrading to Gradle 8.6 only, but that also failed with

```
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /home/sebastian/.gradle/caches/8.6/generated-gradle-jars/gradle-api-8.6.jar!/META-INF/configuration-cache.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
```

So I'm just wondering, is this "by design", and we should keep building the project with some "least common denominator" Gradle version? If so, can we document this somehow?

**Comment by martinbonnin** [comment]
It's definitely not by design :). 

The `DefaultSelfResolvingDependency` thing is a kludge to workaround `java-gradle-plugin` automatically adding `gradleApi()` as an API dependency. This doesn't make sense, it should at least be a compile only dependency and even more probably allow to chose the version (see https://github.com/gradle/gradle/issues/1835).

I'll look into this.

**Comment by martinbonnin** [comment]
Turns out I had a branch with fixes around that. I just opened a PR [there](https://github.com/GradleUp/gr8/pull/22).
